# Generated by Django 2.0.6 on 2018-06-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=40, unique=True)),
                ('in_use', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Available URL',
                'verbose_name_plural': 'Available URLs',
            },
        ),
        migrations.CreateModel(
            name='ShortenedUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_url', models.URLField(unique=True)),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_url', to='url_shortener.AvailableUrls')),
            ],
            options={
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
            },
        ),
    ]
